on:
    push:

concurrency: ci-${{ github.ref }}

name: ci-ecommerce-product-order

env:
    csharp_project: ProductOrder/Ecommerce.ProductOrder.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.csharp_project }} --configfile nuget.config
    - name: Build
      run: |
        dotnet build ${{ env.csharp_project }} --no-restore -c Release